### ISSUE TITLE
Comments from a Quick Code Review

### ISSUE THREAD

**Issue by ccoffrin** [Wikunia/MINLPBnB#52]
Just a bunch of random comments / suggestions.  Nothing major.

**General Questions:**

- Are you keeping the complete tree in memory?  If so, this can be a significant overhead for large problems.
- How the code is broken into files is not super intuitive to me.  Could some of the smaller files be merged?  Or are you anticipating future expansion?

**Some Detailed Comments:**

What would be the difference between an `IncumbentSolution` and a `Solution`?

https://github.com/Wikunia/MINLPBnB/blob/dfa49b6aff454e4a6bb25fa568d27d3337334092/src/BnBTree.jl#L18

Wondering if there is a better name for this, maybe `NodeTypeObj`?

https://github.com/Wikunia/MINLPBnB/blob/dfa49b6aff454e4a6bb25fa568d27d3337334092/src/BnBTree.jl#L43

I believe that [::Nullable{T}](https://docs.julialang.org/en/release-0.4/manual/style-guide/#avoid-type-unions-in-fields) is the preferred design pattern.

https://github.com/Wikunia/MINLPBnB/blob/dfa49b6aff454e4a6bb25fa568d27d3337334092/src/BnBTree.jl#L61-L62

Taking a tip from the PEP8 style guide, function args are easier to read if there is a space after the comma.

https://github.com/Wikunia/MINLPBnB/blob/dfa49b6aff454e4a6bb25fa568d27d3337334092/src/BnBTree.jl#L95

Wondering if there is a better name for this, maybe `expand_node` or `process_node`.  The term leaf is misleading, usually these would refer to only integral nodes in the complete tree, not internal nodes of the partial tree.  In BnB what you call leaves  are often called unexplored/open nodes.

https://github.com/Wikunia/MINLPBnB/blob/dfa49b6aff454e4a6bb25fa568d27d3337334092/src/BnBTree.jl#L128

Am I missing something here?

https://github.com/Wikunia/MINLPBnB/blob/dfa49b6aff454e4a6bb25fa568d27d3337334092/src/BnBTree.jl#L138

When possible use relative paths in imports.  Use of `Pkg.dir()` is discuraged, I forget exactly why.

https://github.com/Wikunia/MINLPBnB/blob/dfa49b6aff454e4a6bb25fa568d27d3337334092/src/MINLPBnB.jl#L35-L37

For cases like this it might be useful to pre-compute once the set of non-`:Cont` variable indexes

https://github.com/Wikunia/MINLPBnB/blob/dfa49b6aff454e4a6bb25fa568d27d3337334092/src/bb_strategies.jl#L11

Semantics should be the same without the `abs`

https://github.com/Wikunia/MINLPBnB/blob/dfa49b6aff454e4a6bb25fa568d27d3337334092/src/bb_type_correct.jl#L23

I don't follow why `1e-2` is hard coded here,

https://github.com/Wikunia/MINLPBnB/blob/dfa49b6aff454e4a6bb25fa568d27d3337334092/src/bb_user_limits.jl#L8

Why not use symbols instead of strings?

https://github.com/Wikunia/MINLPBnB/blob/master/src/table_log.jl#L2

I am not sure this is necessary.  I think options is already a Dict that you can use.

https://github.com/Wikunia/MINLPBnB/blob/dfa49b6aff454e4a6bb25fa568d27d3337334092/src/solver.jl#L40

Why no type for `x` and `obj_expr`?

https://github.com/Wikunia/MINLPBnB/blob/dfa49b6aff454e4a6bb25fa568d27d3337334092/src/model.jl#L15

Are you sure we need all of these?  `:Hess` maybe slow for very large problems.

https://github.com/Wikunia/MINLPBnB/blob/dfa49b6aff454e4a6bb25fa568d27d3337334092/src/model.jl#L112

Should this delegate to the internal NLP solver?

https://github.com/Wikunia/MINLPBnB/blob/dfa49b6aff454e4a6bb25fa568d27d3337334092/src/model.jl#L263

Why store this when you can call `length` on `solution`?

https://github.com/Wikunia/MINLPBnB/blob/dfa49b6aff454e4a6bb25fa568d27d3337334092/src/model.jl#L34

**Comment by Wikunia** [comment]
Thanks for the comments. These are my first thoughts about your questions and comments.

**General**
- I started with storing the whole tree but now I'm just storing the open nodes in `tree.branch_nodes`
- I prefer smaller files instead of one large one that's why I broke things into these smaller ones. 
Are there any disadvantages with several smaller files?

**Details**
- `IncumbentSolution` can be renamed to `Solution`
- `StepObj` is the type which is used to have all information for one branching step (introduced for better parallel computing)
- True `leaf` is normally used for the nodes without children. Good point!
https://github.com/Wikunia/MINLPBnB/blob/dfa49b6aff454e4a6bb25fa568d27d3337334092/src/BnBTree.jl#L138 
Looks unnecessary ;)
- I had a problem with relative paths somehow but can have a look into it again.
- Yes `abs` looks not relevant
- True the default mip gap shouldn't be hard coded there
- I think I can use `:Symbols` for the table log there might be a bit faster, right?
- `options` is of type `Array{Any,1}` and looks like this

```
Array{Any,1}
Any[(:log_levels, Symbol[:Info, :Table, :Timing, :Options]), (:branch_strategy, :Reliability), (:reliability_branching_perc, 25), (:reliability_branching_threshold, 5), (:processors, 1)]
```
that's why I convert it into a dict.

- I'll add a type for `x` and `obj_expr`
- I think I only need `ExprGraph`
- The `setwarmstart` is a leftover from starting with Katana.jl
https://github.com/lanl-ansi/Katana.jl/blob/master/src/model.jl#L335
- `nsolutions` should be actually placed under
https://github.com/Wikunia/MINLPBnB/blob/dfa49b6aff454e4a6bb25fa568d27d3337334092/src/model.jl#L38

There is an option to set `list_of_solutions` which defaults to `false` for not saving unnecessary stuff.
It might be still interesting to know the number of solutions found (at least that was I thought) that's why I store `nsolutions`.

**Comment by Wikunia** [comment]
I just thought about `IncumbentSolution` and `Solution`. I think it might be renamed to `Incumbent` but I wouldn't rename it to `Solution`. For me it sounds fixed in some way. Where as `Incumbent` can be updated.

**Comment by ccoffrin** [comment]
If `IncumbentSolution` is just a holder of metadata specific to the best known solution then I agree `Incumbent` is the right name.  If `IncumbentSolution` is metadata that is relevant to any feasible solution it should have a more general name.  Like `SolutionInfo` or maybe `SolutionMetadata`, or just `Solution`.
